#!/usr/local/bin/ruby -w

require 'inline'

name = ARGV.shift
version = ARGV.shift
summary = ARGV.shift || ""

if version.nil? then # TODO better usage
  STDERR.puts "Usage: #{$0} NAME VERSION [SUMMARY]"
  exit 1
end

packager = Inline::Packager.new name, version, summary
packager.package
